#!/usr/bin/env python3
"""Assemble the manuscript's supplementary tables from the results tables.

Each supplementary table is a thin, documented view of a file in
`results/tables/` — never a separate calculation — so a reviewer can trace any
supplementary number back to the pipeline that produced it.

Outputs: manuscript/supplementary/S*.csv and manuscript/supplementary/README.md
"""
from __future__ import annotations

import sys
from pathlib import Path

import pandas as pd

sys.path.insert(0, str(Path(__file__).resolve().parent))
from lib_sources import RESULTS, ROOT, SITE_DATA, get_json, log  # noqa: E402

T, E = RESULTS / "tables", RESULTS / "enrichment"
OUT = ROOT / "manuscript" / "supplementary"

DESCRIPTIONS = {
    "S1_regolith_study_catalogue.csv":
        "Every regolith-relevant study in NASA OSDR and every curated investigation in "
        "NASA PSI, with measured file and image counts and the reason each is included. "
        "From public/data/osdr_regolith_catalog.json and psi_regolith_catalog.json.",
    "S2_growth_correlated_genes.csv":
        "All gene x covariate correlations significant at 5% FDR in either analysis, with "
        "Spearman rho, raw and adjusted p, and gene annotation. From "
        "results/tables/growth_correlated_genes.csv.gz.",
    "S3_robust_growth_genes.csv":
        "The 361 gene x covariate pairs significant in both the primary and within-lunar "
        "analyses with a consistent sign. From results/tables/growth_genes_robust.csv.",
    "S4_sample_phenotype_map.csv":
        "The join between every OSD-476 RNA-seq sample and its growth: plate, join "
        "confidence, leaf trajectory summaries and PlantCV shape covariates. From "
        "results/tables/sample_phenotype_expression_map.csv.",
    "S5_goslim_enrichment.csv":
        "GO-slim over-representation results for every gene set tested, including terms "
        "that did not pass FDR. From results/enrichment/goslim_enrichment.csv.",
    "S6_substrate_characterisation.csv":
        "Endpoint soil-probe readings for the eight substrates, and the LHS-1 versus "
        "Chang'e-5 oxide comparison. From results/tables/substrate_*.csv.",
    "S7_sowing_date_check.csv":
        "Per-sample candidate sowing dates implied by the deposited age at harvest and "
        "leaf count. The intersection is empty; see Methods. From "
        "results/tables/sowing_date_check.csv.",
}


def catalogue() -> pd.DataFrame:
    osdr = get_json_file(SITE_DATA / "osdr_regolith_catalog.json")
    psi = get_json_file(SITE_DATA / "psi_regolith_catalog.json")
    rows = [{
        "repository": "NASA OSDR", "accession": s["accession"], "title": s["title"],
        "organism": s["organism"], "factors": s["factors"],
        "measurements": s["measurements"], "released": s["released"],
        "files": s["files"], "images": s["images"], "image_mb": s["image_mb"],
        "reason_included": s["why_regolith"], "url": s["url"],
    } for s in osdr["studies"]]
    rows += [{
        "repository": "NASA PSI", "accession": s["accession"], "title": s["title"],
        "organism": "", "factors": s["research_area"], "measurements": s["project_type"],
        "released": s["start"], "files": "", "images": "", "image_mb": "",
        "reason_included": s["relevance"], "url": s["url"],
    } for s in psi["curated"]]
    return pd.DataFrame(rows)


def get_json_file(path: Path):
    import json
    return json.loads(path.read_text())


def main() -> int:
    OUT.mkdir(parents=True, exist_ok=True)

    catalogue().to_csv(OUT / "S1_regolith_study_catalogue.csv", index=False)

    g = pd.read_csv(T / "growth_correlated_genes.csv.gz")
    ann = pd.read_csv(T / "gene_annotation.csv").set_index("gene")
    (g[g["fdr"] < 0.05].join(ann, on="gene")
     .sort_values(["analysis", "covariate", "fdr"])
     .to_csv(OUT / "S2_growth_correlated_genes.csv", index=False))

    pd.read_csv(T / "growth_genes_robust.csv").to_csv(
        OUT / "S3_robust_growth_genes.csv", index=False)
    pd.read_csv(T / "sample_phenotype_expression_map.csv").to_csv(
        OUT / "S4_sample_phenotype_map.csv", index=False)
    pd.read_csv(E / "goslim_enrichment.csv").to_csv(
        OUT / "S5_goslim_enrichment.csv", index=False)

    probe = pd.read_csv(T / "substrate_probe_endpoint.csv").assign(table="probe_endpoint")
    chem = pd.read_csv(T / "substrate_chemistry_comparison.csv").assign(table="oxide_comparison")
    pd.concat([probe, chem], ignore_index=True).to_csv(
        OUT / "S6_substrate_characterisation.csv", index=False)

    pd.read_csv(T / "sowing_date_check.csv").to_csv(
        OUT / "S7_sowing_date_check.csv", index=False)

    lines = ["# Supplementary tables", "",
             "Generated by `scripts/12_supplementary_tables.py`. Each is a view of a file in",
             "`results/tables/` or `results/enrichment/`, so every supplementary number traces",
             "back to the pipeline in `scripts/`.", "",
             "| Table | Rows | Description |", "| --- | --- | --- |"]
    for name, desc in DESCRIPTIONS.items():
        n = len(pd.read_csv(OUT / name))
        lines.append(f"| [`{name}`]({name}) | {n:,} | {desc} |")
        log(f"  ✓ {name}  ({n:,} rows)")
    (OUT / "README.md").write_text("\n".join(lines) + "\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
